# Generated by Django 4.2.3 on 2023-08-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64, null=True)),
                ('number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=64)),
                ('telegram_id', models.CharField(max_length=64, null=True)),
                ('orders_count', models.IntegerField()),
                ('permissions', models.JSONField(null=True)),
                ('availableToday', models.BooleanField(null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='CompanyOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=128, null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Статус заказа компании',
                'verbose_name_plural': 'Статусы заказов компании',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100, verbose_name='lab_name')),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Тип новости',
                'verbose_name_plural': 'Типы новостей',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=128, null=True, verbose_name='role')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='PS.basicuser')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.lab')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('order_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('exec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exec_of', to='PS.basicuser')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.lab')),
                ('order_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_created_by', to='PS.basicuser')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.orderstatus')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256)),
                ('picture', models.BinaryField(null=True)),
                ('content', models.CharField(max_length=1028)),
                ('telegram_post', models.BooleanField(default=False)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.basicuser')),
                ('news_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.newstype')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('order_name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('exec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_exec_of', to='PS.basicuser')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.lab')),
                ('order_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_orders_created_by', to='PS.basicuser')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.companyorderstatus')),
            ],
            options={
                'verbose_name': 'Заказ компании',
                'verbose_name_plural': 'Заказы компании',
            },
        ),
        migrations.AddField(
            model_name='basicuser',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.lab'),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.role'),
        ),
    ]
