# Generated by Django 4.2.3 on 2023-07-31 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='firstname')),
                ('surname', models.CharField(max_length=64, null=True, verbose_name='surname')),
                ('number', models.CharField(max_length=12, verbose_name='number')),
                ('email', models.CharField(max_length=64, verbose_name='email')),
                ('telegram_id', models.CharField(max_length=64, null=True, verbose_name='telegram_id')),
                ('orders_count', models.IntegerField(verbose_name='orders_count')),
                ('permissions', models.JSONField(null=True, verbose_name='permissions')),
                ('availableToday', models.BooleanField(null=True, verbose_name='available_today')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='reg_date')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='CompanyOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=128, null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'company_order_status_enum',
                'verbose_name_plural': 'company_order_status_enum',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100, verbose_name='lab_name')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, null=True, verbose_name='news_type')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=128, null=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=128, null=True, verbose_name='role')),
            ],
            options={
                'verbose_name': 'role_enum',
                'verbose_name_plural': 'role_enum',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.basicuser')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='reg_date')),
                ('order_name', models.CharField(max_length=128, verbose_name='order_name')),
                ('description', models.CharField(max_length=1024, null=True, verbose_name='description')),
                ('deadline', models.DateTimeField(null=True, verbose_name='deadline')),
                ('exec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.basicuser')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.lab')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.orderstatus')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256, verbose_name='header')),
                ('content', models.CharField(max_length=1028, verbose_name='content')),
                ('telegram_post', models.BooleanField(default=False, verbose_name='telegram_post')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='post_date')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.basicuser')),
                ('news_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.newstypes')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='reg_date')),
                ('order_name', models.CharField(max_length=128, verbose_name='order_name')),
                ('description', models.CharField(max_length=1024, null=True, verbose_name='description')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.lab')),
                ('status', models.ForeignKey(default='created', on_delete=django.db.models.deletion.CASCADE, to='PS.companyorderstatus')),
            ],
        ),
        migrations.AddField(
            model_name='basicuser',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.lab'),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.role'),
        ),
    ]
