# Generated by Django 4.2.3 on 2023-07-30 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderinproccess',
            options={'verbose_name': 'Заказ в работе', 'verbose_name_plural': 'Заказы в работе'},
        ),
        migrations.AlterModelOptions(
            name='orderpaid',
            options={'verbose_name': 'Оплаченный заказ', 'verbose_name_plural': 'Оплаченные заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.role'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.basicuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.orderstatus'),
        ),
    ]
