# Generated by Django 4.2.3 on 2023-07-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(),
        ),
    ]
