# Generated by Django 4.2.3 on 2023-07-31 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PS', '0002_alter_basicuser_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOrderComplete',
            fields=[
                ('companyorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PS.companyorder')),
            ],
            options={
                'verbose_name': 'order_placed',
                'verbose_name_plural': 'order_placed',
            },
            bases=('PS.companyorder',),
        ),
        migrations.CreateModel(
            name='CompanyOrderProccess',
            fields=[
                ('companyorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PS.companyorder')),
            ],
            options={
                'verbose_name': 'order_placed',
                'verbose_name_plural': 'order_placed',
            },
            bases=('PS.companyorder',),
        ),
        migrations.RenameField(
            model_name='role',
            old_name='RoleName',
            new_name='role_name',
        ),
    ]
