# Generated by Django 4.2.3 on 2023-07-31 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PS', '0003_companyordercomplete_companyorderproccess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128, null=True, verbose_name='news_type')),
            ],
        ),
        migrations.AddField(
            model_name='basicuser',
            name='availableToday',
            field=models.BooleanField(null=True, verbose_name='available_today'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.basicuser')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.lab')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=256, verbose_name='header')),
                ('content', models.CharField(max_length=1028, verbose_name='content')),
                ('telegram_post', models.BooleanField(default=False, verbose_name='telegram_post')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='post_date')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.basicuser')),
                ('news_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PS.newstypes')),
            ],
        ),
    ]
